- name: Install Homebrew packages
  tags:
    - homebrew
  command: brew install "{{ item }}"
  with_items:
    - ack
    - asciinema
    - asciiquarium
    - curl
    - git
    - redis
    - sl
    - sqlite
    - thefuck
    - tree
    - wget
